// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: mutual_exclusion.proto

package mutual_exclusion

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MutualExclusionService_Request_FullMethodName = "/mutual_exclusion.MutualExclusionService/Request"
	MutualExclusionService_Grant_FullMethodName   = "/mutual_exclusion.MutualExclusionService/Grant"
	MutualExclusionService_Release_FullMethodName = "/mutual_exclusion.MutualExclusionService/Release"
)

// MutualExclusionServiceClient is the client API for MutualExclusionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MutualExclusionServiceClient interface {
	Request(ctx context.Context, in *RequestAccess, opts ...grpc.CallOption) (*Empty, error)
	Grant(ctx context.Context, in *GrantAccess, opts ...grpc.CallOption) (*Empty, error)
	Release(ctx context.Context, in *ReleaseAccess, opts ...grpc.CallOption) (*Empty, error)
}

type mutualExclusionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMutualExclusionServiceClient(cc grpc.ClientConnInterface) MutualExclusionServiceClient {
	return &mutualExclusionServiceClient{cc}
}

func (c *mutualExclusionServiceClient) Request(ctx context.Context, in *RequestAccess, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MutualExclusionService_Request_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mutualExclusionServiceClient) Grant(ctx context.Context, in *GrantAccess, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MutualExclusionService_Grant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mutualExclusionServiceClient) Release(ctx context.Context, in *ReleaseAccess, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MutualExclusionService_Release_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MutualExclusionServiceServer is the server API for MutualExclusionService service.
// All implementations must embed UnimplementedMutualExclusionServiceServer
// for forward compatibility.
type MutualExclusionServiceServer interface {
	Request(context.Context, *RequestAccess) (*Empty, error)
	Grant(context.Context, *GrantAccess) (*Empty, error)
	Release(context.Context, *ReleaseAccess) (*Empty, error)
	mustEmbedUnimplementedMutualExclusionServiceServer()
}

// UnimplementedMutualExclusionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMutualExclusionServiceServer struct{}

func (UnimplementedMutualExclusionServiceServer) Request(context.Context, *RequestAccess) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedMutualExclusionServiceServer) Grant(context.Context, *GrantAccess) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Grant not implemented")
}
func (UnimplementedMutualExclusionServiceServer) Release(context.Context, *ReleaseAccess) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Release not implemented")
}
func (UnimplementedMutualExclusionServiceServer) mustEmbedUnimplementedMutualExclusionServiceServer() {
}
func (UnimplementedMutualExclusionServiceServer) testEmbeddedByValue() {}

// UnsafeMutualExclusionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MutualExclusionServiceServer will
// result in compilation errors.
type UnsafeMutualExclusionServiceServer interface {
	mustEmbedUnimplementedMutualExclusionServiceServer()
}

func RegisterMutualExclusionServiceServer(s grpc.ServiceRegistrar, srv MutualExclusionServiceServer) {
	// If the following call pancis, it indicates UnimplementedMutualExclusionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MutualExclusionService_ServiceDesc, srv)
}

func _MutualExclusionService_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAccess)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MutualExclusionServiceServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MutualExclusionService_Request_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MutualExclusionServiceServer).Request(ctx, req.(*RequestAccess))
	}
	return interceptor(ctx, in, info, handler)
}

func _MutualExclusionService_Grant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantAccess)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MutualExclusionServiceServer).Grant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MutualExclusionService_Grant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MutualExclusionServiceServer).Grant(ctx, req.(*GrantAccess))
	}
	return interceptor(ctx, in, info, handler)
}

func _MutualExclusionService_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseAccess)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MutualExclusionServiceServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MutualExclusionService_Release_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MutualExclusionServiceServer).Release(ctx, req.(*ReleaseAccess))
	}
	return interceptor(ctx, in, info, handler)
}

// MutualExclusionService_ServiceDesc is the grpc.ServiceDesc for MutualExclusionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MutualExclusionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mutual_exclusion.MutualExclusionService",
	HandlerType: (*MutualExclusionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _MutualExclusionService_Request_Handler,
		},
		{
			MethodName: "Grant",
			Handler:    _MutualExclusionService_Grant_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _MutualExclusionService_Release_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mutual_exclusion.proto",
}
