// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.1
// source: mutual_exclusion.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestAccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId    int32 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *RequestAccess) Reset() {
	*x = RequestAccess{}
	mi := &file_mutual_exclusion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAccess) ProtoMessage() {}

func (x *RequestAccess) ProtoReflect() protoreflect.Message {
	mi := &file_mutual_exclusion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAccess.ProtoReflect.Descriptor instead.
func (*RequestAccess) Descriptor() ([]byte, []int) {
	return file_mutual_exclusion_proto_rawDescGZIP(), []int{0}
}

func (x *RequestAccess) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *RequestAccess) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GrantAccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId int32 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
}

func (x *GrantAccess) Reset() {
	*x = GrantAccess{}
	mi := &file_mutual_exclusion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantAccess) ProtoMessage() {}

func (x *GrantAccess) ProtoReflect() protoreflect.Message {
	mi := &file_mutual_exclusion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantAccess.ProtoReflect.Descriptor instead.
func (*GrantAccess) Descriptor() ([]byte, []int) {
	return file_mutual_exclusion_proto_rawDescGZIP(), []int{1}
}

func (x *GrantAccess) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type ReleaseAccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId int32 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
}

func (x *ReleaseAccess) Reset() {
	*x = ReleaseAccess{}
	mi := &file_mutual_exclusion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseAccess) ProtoMessage() {}

func (x *ReleaseAccess) ProtoReflect() protoreflect.Message {
	mi := &file_mutual_exclusion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseAccess.ProtoReflect.Descriptor instead.
func (*ReleaseAccess) Descriptor() ([]byte, []int) {
	return file_mutual_exclusion_proto_rawDescGZIP(), []int{2}
}

func (x *ReleaseAccess) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_mutual_exclusion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_mutual_exclusion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_mutual_exclusion_proto_rawDescGZIP(), []int{3}
}

var File_mutual_exclusion_proto protoreflect.FileDescriptor

var file_mutual_exclusion_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6d, 0x75, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x6d, 0x75, 0x74, 0x75, 0x61, 0x6c,
	0x5f, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x46, 0x0a, 0x0d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x6e,
	0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x6f,
	0x64, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x22, 0x26, 0x0a, 0x0b, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x22, 0x28, 0x0a, 0x0d, 0x52, 0x65,
	0x6c, 0x65, 0x61, 0x73, 0x65, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x6e,
	0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x6f,
	0x64, 0x65, 0x49, 0x64, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0xe3, 0x01,
	0x0a, 0x16, 0x4d, 0x75, 0x74, 0x75, 0x61, 0x6c, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x6f,
	0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1f, 0x2e, 0x6d, 0x75, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x65, 0x78, 0x63,
	0x6c, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x1a, 0x17, 0x2e, 0x6d, 0x75, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x65, 0x78,
	0x63, 0x6c, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3f, 0x0a,
	0x05, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x12, 0x1d, 0x2e, 0x6d, 0x75, 0x74, 0x75, 0x61, 0x6c, 0x5f,
	0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x41,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x1a, 0x17, 0x2e, 0x6d, 0x75, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x65,
	0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x43,
	0x0a, 0x07, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x1f, 0x2e, 0x6d, 0x75, 0x74, 0x75,
	0x61, 0x6c, 0x5f, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x6c,
	0x65, 0x61, 0x73, 0x65, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x1a, 0x17, 0x2e, 0x6d, 0x75, 0x74,
	0x75, 0x61, 0x6c, 0x5f, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2f, 0x6d, 0x75, 0x74, 0x75, 0x61, 0x6c, 0x5f,
	0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_mutual_exclusion_proto_rawDescOnce sync.Once
	file_mutual_exclusion_proto_rawDescData = file_mutual_exclusion_proto_rawDesc
)

func file_mutual_exclusion_proto_rawDescGZIP() []byte {
	file_mutual_exclusion_proto_rawDescOnce.Do(func() {
		file_mutual_exclusion_proto_rawDescData = protoimpl.X.CompressGZIP(file_mutual_exclusion_proto_rawDescData)
	})
	return file_mutual_exclusion_proto_rawDescData
}

var file_mutual_exclusion_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mutual_exclusion_proto_goTypes = []any{
	(*RequestAccess)(nil), // 0: mutual_exclusion.RequestAccess
	(*GrantAccess)(nil),   // 1: mutual_exclusion.GrantAccess
	(*ReleaseAccess)(nil), // 2: mutual_exclusion.ReleaseAccess
	(*Empty)(nil),         // 3: mutual_exclusion.Empty
}
var file_mutual_exclusion_proto_depIdxs = []int32{
	0, // 0: mutual_exclusion.MutualExclusionService.Request:input_type -> mutual_exclusion.RequestAccess
	1, // 1: mutual_exclusion.MutualExclusionService.Grant:input_type -> mutual_exclusion.GrantAccess
	2, // 2: mutual_exclusion.MutualExclusionService.Release:input_type -> mutual_exclusion.ReleaseAccess
	3, // 3: mutual_exclusion.MutualExclusionService.Request:output_type -> mutual_exclusion.Empty
	3, // 4: mutual_exclusion.MutualExclusionService.Grant:output_type -> mutual_exclusion.Empty
	3, // 5: mutual_exclusion.MutualExclusionService.Release:output_type -> mutual_exclusion.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mutual_exclusion_proto_init() }
func file_mutual_exclusion_proto_init() {
	if File_mutual_exclusion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mutual_exclusion_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mutual_exclusion_proto_goTypes,
		DependencyIndexes: file_mutual_exclusion_proto_depIdxs,
		MessageInfos:      file_mutual_exclusion_proto_msgTypes,
	}.Build()
	File_mutual_exclusion_proto = out.File
	file_mutual_exclusion_proto_rawDesc = nil
	file_mutual_exclusion_proto_goTypes = nil
	file_mutual_exclusion_proto_depIdxs = nil
}
